---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: "daily"
      time: "03:27"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
  - package-ecosystem: docker
    directory: "/docker2"
    schedule:
      interval: "daily"
      time: "04:07"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
  - package-ecosystem: docker
    directory: "/docker3"
    schedule:
      interval: "daily"
      time: "04:07"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
  - package-ecosystem: docker
    directory: "/docker4"
    schedule:
      interval: "daily"
      time: "09:46"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
